//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FlorecerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public long AppointmentId { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool Status { get; set; }
        public long UserId { get; set; }
        public long AppointmentType { get; set; }
    
        public virtual AppointmentTypes AppointmentTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
