//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FlorecerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalTests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalTests()
        {
            this.TestResults = new HashSet<TestResults>();
        }
    
        public long TestId { get; set; }
        public string TestName { get; set; }
        public string Description { get; set; }
        public string TestType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResults> TestResults { get; set; }
    }
}
