//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FlorecerApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlorecerAppEntities : DbContext
    {
        public FlorecerAppEntities()
            : base("name=FlorecerAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<AppointmentTypes> AppointmentTypes { get; set; }
        public virtual DbSet<Binnacle> Binnacle { get; set; }
        public virtual DbSet<MedicalPersonnel> MedicalPersonnel { get; set; }
        public virtual DbSet<MedicalTests> MedicalTests { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<TestResults> TestResults { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
