//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FlorecerApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlorecerAppEntities : DbContext
    {
        public FlorecerAppEntities()
            : base("name=FlorecerAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Binnacle> Binnacle { get; set; }
        public virtual DbSet<MedicalPersonnel> MedicalPersonnel { get; set; }
        public virtual DbSet<MedicalTests> MedicalTests { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<TestResults> TestResults { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
