//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FlorecerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public long ResultId { get; set; }
        public Nullable<long> PatientId { get; set; }
        public Nullable<long> PersonnelId { get; set; }
        public Nullable<long> TestId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Score { get; set; }
    
        public virtual MedicalPersonnel MedicalPersonnel { get; set; }
        public virtual MedicalTests MedicalTests { get; set; }
        public virtual Users Users { get; set; }
    }
}
