//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FlorecerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public long ResultId { get; set; }
        public Nullable<long> PatientId { get; set; }
        public Nullable<long> PersonnelId { get; set; }
        public Nullable<long> TestId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Score { get; set; }
    
        public virtual MedicalPersonnel MedicalPersonnel { get; set; }
        public virtual MedicalTest MedicalTest { get; set; }
        public virtual User User { get; set; }
    }
}
